import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const DATA_DIR = path.join(process.cwd(), 'data');
const CALLS_FILE = path.join(DATA_DIR, 'calls.json');
const LEADS_FILE = path.join(DATA_DIR, 'leads.json');

interface CallRecord {
  callId: string;
  leadId?: string;
  timestamp: string;
  status: string;
  duration?: number;
  endedReason?: string;
  summary?: string;
  transcript?: string;
  structuredData?: Record<string, unknown>;
  email?: string;
  customerName?: string;
  companyName?: string;
  phone?: string;
}

interface Lead {
  leadId: string;
  name: string;
  phone: string;
  email: string;
  companyName: string;
  [key: string]: unknown;
}

async function readCalls(): Promise<CallRecord[]> {
  try {
    const raw = await fs.readFile(CALLS_FILE, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

async function writeCalls(calls: CallRecord[]): Promise<void> {
  await fs.mkdir(DATA_DIR, { recursive: true });
  await fs.writeFile(CALLS_FILE, JSON.stringify(calls, null, 2));
}

async function readLeads(): Promise<Lead[]> {
  try {
    const raw = await fs.readFile(LEADS_FILE, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

function buildEmailHtml(lead: Lead, callRecord: CallRecord): string {
  const sd = (callRecord.structuredData || {}) as Record<string, string | boolean | number | null>;
  const name = lead.name || sd.customer_name || 'there';
  const appUrl = process.env.NEXTAUTH_URL || 'http://okg4gks008k4ko8ckow4cwwo.62.171.142.50.sslip.io';

  const rows = [
    ['Name', lead.name || 'N/A'],
    ['Phone', lead.phone || 'N/A'],
    ['Email', lead.email || 'N/A'],
    ['Company', lead.companyName || 'N/A'],
    ['Business Type', str(sd.business_type)],
    ['Wants Follow-up', sd.wants_follow_up === true ? 'Yes' : sd.wants_follow_up === false ? 'No' : 'Not discussed'],
    ['Preferred Follow-up Time', str(sd.follow_up_time_preference)],
    ['Lead Volume', str(sd.lead_volume)],
    ['Service Interest', str(sd.service_interest)],
    ['Current Process', str(sd.current_lead_process)],
    ['Pain Points', str(sd.pain_points)],
    ['Channels Used', str(sd.channels_used)],
    ['Qualification Score', sd.qualification_score ? `${sd.qualification_score}/10` : 'N/A'],
  ];

  const tableRows = rows
    .map(([label, value]) => `<tr><td style="padding:8px 12px;font-weight:bold;border:1px solid #e2e8f0;">${label}</td><td style="padding:8px 12px;border:1px solid #e2e8f0;">${value}</td></tr>`)
    .join('\n');

  const summary = callRecord.summary || 'Summary not available.';
  const nextStep = str(sd.recommended_next_step);

  // Transcript snippet (first 500 chars)
  const transcript = callRecord.transcript
    ? callRecord.transcript.slice(0, 500) + (callRecord.transcript.length > 500 ? '...' : '')
    : '';

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;color:#1a202c;background:#f7fafc;padding:20px;">
  <div style="background:#ffffff;border-radius:8px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <h2 style="color:#2d3748;margin-top:0;">LeadCall AI — Call Summary</h2>
    <p>Hi ${name},</p>
    <p>Thanks for taking the call. Here is your qualification summary.</p>
    
    <table style="width:100%;border-collapse:collapse;margin:20px 0;">
      ${tableRows}
    </table>

    <h3 style="color:#2d3748;">Summary</h3>
    <p style="background:#f7fafc;padding:12px;border-radius:4px;border-left:3px solid #4299e1;">${summary}</p>

    ${nextStep !== 'N/A' ? `<h3 style="color:#2d3748;">Recommended Next Step</h3><p>${nextStep}</p>` : ''}

    ${transcript ? `<h3 style="color:#2d3748;">Transcript Snippet</h3><p style="font-size:13px;color:#718096;background:#f7fafc;padding:12px;border-radius:4px;">${transcript}</p>` : ''}

    <div style="text-align:center;margin:28px 0 12px;">
      <a href="${appUrl}" style="display:inline-block;background:#4299e1;color:#ffffff;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;">Learn More About LeadCall AI →</a>
    </div>

    <p style="font-size:12px;color:#a0aec0;margin-top:24px;">This email was generated by LeadCall AI after your demo call. If you have questions, simply reply to this email.</p>
  </div>
</body>
</html>`;
}

function str(val: unknown): string {
  if (val === null || val === undefined || val === '' || val === 'null') return 'N/A';
  const s = String(val).trim();
  return s.length > 0 ? s : 'N/A';
}

export async function POST(req: NextRequest) {
  // Verify optional token
  const expectedToken = process.env.VAPI_WEBHOOK_TOKEN;
  if (expectedToken) {
    const authHeader = req.headers.get('authorization') || '';
    const token = authHeader.replace(/^Bearer\s+/i, '').trim();
    if (token !== expectedToken) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const payload = body as Record<string, unknown>;
  const message = (payload.message as Record<string, unknown>) || payload;
  const messageType = (message.type as string) || (payload.type as string) || '';

  // Only process end-of-call-report
  if (messageType !== 'end-of-call-report') {
    return NextResponse.json({ received: true, type: messageType });
  }

  const call = (message.call as Record<string, unknown>) || {};
  const callId = (call.id as string) || (payload.callId as string) || 'unknown';
  const endedReason = (message.endedReason as string) || (call.endedReason as string) || '';

  // Extract variable values (form data passed when call was created)
  const overrides = (call.assistantOverrides as Record<string, unknown>) || {};
  const variableValues = (overrides.variableValues as Record<string, string>) || {};

  // Also check metadata
  const metadata = (overrides.metadata as Record<string, string>) || {};

  const analysis = (message.analysis as Record<string, unknown>) || {};
  const artifact = (message.artifact as Record<string, unknown>) || {};

  const structuredData = (analysis.structuredData as Record<string, unknown>) ||
    (artifact.structuredData as Record<string, unknown>) || {};

  const callRecord: CallRecord = {
    callId,
    leadId: variableValues.leadId || metadata.leadId || undefined,
    timestamp: new Date().toISOString(),
    status: messageType,
    endedReason,
    duration: call.duration as number | undefined,
    summary: (analysis.summary as string) || (artifact.summary as string) || undefined,
    transcript: (artifact.transcript as string) || undefined,
    structuredData,
    email: variableValues.email || metadata.email || undefined,
    customerName: variableValues.name || metadata.customerName || (structuredData.customer_name as string) || undefined,
    companyName: variableValues.companyName || metadata.companyName || (structuredData.company_name as string) || undefined,
    phone: variableValues.phone || metadata.phone || undefined,
  };

  // Persist
  const calls = await readCalls();
  const existingIdx = calls.findIndex((c) => c.callId === callId);
  if (existingIdx !== -1) {
    calls[existingIdx] = { ...calls[existingIdx], ...callRecord };
  } else {
    calls.unshift(callRecord);
  }
  await writeCalls(calls);

  // Find original lead data for complete info
  const leads = await readLeads();
  const lead: Lead = leads.find((l) => l.leadId === callRecord.leadId) || {
    leadId: callRecord.leadId || '',
    name: callRecord.customerName || '',
    phone: callRecord.phone || '',
    email: callRecord.email || '',
    companyName: callRecord.companyName || '',
  };

  // Send email if we have an address
  const recipientEmail = lead.email || callRecord.email;
  if (recipientEmail) {
    const emailHtml = buildEmailHtml(lead, callRecord);

    // Try n8n email-send webhook first (just to send email, not to generate it)
    const n8nWebhook = process.env.N8N_DEMO_WEBHOOK;
    if (n8nWebhook) {
      try {
        await fetch(n8nWebhook, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            event: 'send_email',
            to: recipientEmail,
            subject: `Your LeadCall AI Demo — Call Summary for ${lead.companyName || 'Your Business'}`,
            html: emailHtml,
            // Also pass raw data for n8n logging
            callId,
            leadId: callRecord.leadId,
            customerName: lead.name,
            companyName: lead.companyName,
            phone: lead.phone,
          }),
        });
        console.log('[email] Sent via n8n for', recipientEmail);
      } catch (err) {
        console.error('[email] n8n send failed:', err);
      }
    }
  }

  return NextResponse.json({ received: true, callId });
}
